import Head from "next/head";
import Link from "next/link";
import AppLayout from "../components/layouts/AppLayout";
import { NextPageWithLayout } from "@/pages/_app";
// import { trpc } from "@/utils/trpc";

const Home: NextPageWithLayout = () => {
  // const mutation = trpc.useMutation("user.update");
  return (
    <>
      <Head>
        <title>Ricardodelmonte.com | Patient Handler</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto mt-16 max-w-7xl px-4 sm:mt-24">
        <div className="text-center">
          <h1 className="text-4xl font-bold tracking-tight text-gray-900 sm:text-5xl md:text-6xl">
            <span className="block xl:inline">Manejador</span>{" "}
            <span className="block text-indigo-600 xl:inline">de pacientes</span>
          </h1>
          <p className="mx-auto mt-3 max-w-md text-base text-gray-500 sm:text-lg md:mt-5 md:max-w-3xl md:text-xl">
            Pagina utilitaria para el manejo de pacientes del Dr. Ricardo Delmonte
          </p>
          <div className="mx-auto mt-5 max-w-md sm:flex sm:justify-center md:mt-8">
            <div className="rounded-md shadow">
              <Link href="/nuevo-paciente">
                <a className="flex w-full items-center justify-center rounded-md border border-transparent bg-indigo-600 px-8 py-3 text-base font-medium text-white hover:bg-indigo-700 md:py-4 md:px-10 md:text-lg">
                  Nuevo Paciente
                </a>
              </Link>
              {/* <button onClick={() => mutation.mutate({ username: "ricardodelmonte" })}>
                hash ricardos pw
              </button> */}
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

Home.layout = AppLayout;

export default Home;
